// Code generated by MockGen. DO NOT EDIT.
// Source: orders.go
//
// Generated by this command:
//
//	mockgen -source=orders.go -destination=orders_mock.go -package=orders
//

// Package orders is a generated GoMock package.
package orders

import (
	context "context"
	domain "gmart/internal/domain"
	dto "gmart/internal/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepoIFace is a mock of OrdersRepoIFace interface.
type MockOrdersRepoIFace struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepoIFaceMockRecorder
	isgomock struct{}
}

// MockOrdersRepoIFaceMockRecorder is the mock recorder for MockOrdersRepoIFace.
type MockOrdersRepoIFaceMockRecorder struct {
	mock *MockOrdersRepoIFace
}

// NewMockOrdersRepoIFace creates a new mock instance.
func NewMockOrdersRepoIFace(ctrl *gomock.Controller) *MockOrdersRepoIFace {
	mock := &MockOrdersRepoIFace{ctrl: ctrl}
	mock.recorder = &MockOrdersRepoIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepoIFace) EXPECT() *MockOrdersRepoIFaceMockRecorder {
	return m.recorder
}

// AcquireNextOrder mocks base method.
func (m *MockOrdersRepoIFace) AcquireNextOrder(ctx context.Context) (domain.OrderNumber, domain.OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireNextOrder", ctx)
	ret0, _ := ret[0].(domain.OrderNumber)
	ret1, _ := ret[1].(domain.OrderStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcquireNextOrder indicates an expected call of AcquireNextOrder.
func (mr *MockOrdersRepoIFaceMockRecorder) AcquireNextOrder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireNextOrder", reflect.TypeOf((*MockOrdersRepoIFace)(nil).AcquireNextOrder), ctx)
}

// List mocks base method.
func (m *MockOrdersRepoIFace) List(ctx context.Context, userID domain.UserID) ([]dto.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]dto.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrdersRepoIFaceMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrdersRepoIFace)(nil).List), ctx, userID)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrdersRepoIFace) UpdateOrderStatus(ctx context.Context, orderNumber domain.OrderNumber, orderStatus domain.OrderStatus, accrual domain.Amount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderNumber, orderStatus, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrdersRepoIFaceMockRecorder) UpdateOrderStatus(ctx, orderNumber, orderStatus, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrdersRepoIFace)(nil).UpdateOrderStatus), ctx, orderNumber, orderStatus, accrual)
}

// Upload mocks base method.
func (m *MockOrdersRepoIFace) Upload(ctx context.Context, userID domain.UserID, orderNumber domain.OrderNumber) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockOrdersRepoIFaceMockRecorder) Upload(ctx, userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockOrdersRepoIFace)(nil).Upload), ctx, userID, orderNumber)
}
