// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock_test.go -package=orders
//

// Package orders is a generated GoMock package.
package orders

import (
	domain "gmart/internal/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersMetrics is a mock of OrdersMetrics interface.
type MockOrdersMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersMetricsMockRecorder
	isgomock struct{}
}

// MockOrdersMetricsMockRecorder is the mock recorder for MockOrdersMetrics.
type MockOrdersMetricsMockRecorder struct {
	mock *MockOrdersMetrics
}

// NewMockOrdersMetrics creates a new mock instance.
func NewMockOrdersMetrics(ctrl *gomock.Controller) *MockOrdersMetrics {
	mock := &MockOrdersMetrics{ctrl: ctrl}
	mock.recorder = &MockOrdersMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersMetrics) EXPECT() *MockOrdersMetricsMockRecorder {
	return m.recorder
}

// IncOrderUpload mocks base method.
func (m *MockOrdersMetrics) IncOrderUpload(status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncOrderUpload", status)
}

// IncOrderUpload indicates an expected call of IncOrderUpload.
func (mr *MockOrdersMetricsMockRecorder) IncOrderUpload(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncOrderUpload", reflect.TypeOf((*MockOrdersMetrics)(nil).IncOrderUpload), status)
}

// ObserveDB mocks base method.
func (m *MockOrdersMetrics) ObserveDB(op domain.OpType, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDB", op, duration)
}

// ObserveDB indicates an expected call of ObserveDB.
func (mr *MockOrdersMetricsMockRecorder) ObserveDB(op, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDB", reflect.TypeOf((*MockOrdersMetrics)(nil).ObserveDB), op, duration)
}

// ObserveListSize mocks base method.
func (m *MockOrdersMetrics) ObserveListSize(size int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveListSize", size)
}

// ObserveListSize indicates an expected call of ObserveListSize.
func (mr *MockOrdersMetricsMockRecorder) ObserveListSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveListSize", reflect.TypeOf((*MockOrdersMetrics)(nil).ObserveListSize), size)
}
