// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock_test.go -package=user
//

// Package user is a generated GoMock package.
package user

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthMetrics is a mock of AuthMetrics interface.
type MockAuthMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMetricsMockRecorder
	isgomock struct{}
}

// MockAuthMetricsMockRecorder is the mock recorder for MockAuthMetrics.
type MockAuthMetricsMockRecorder struct {
	mock *MockAuthMetrics
}

// NewMockAuthMetrics creates a new mock instance.
func NewMockAuthMetrics(ctrl *gomock.Controller) *MockAuthMetrics {
	mock := &MockAuthMetrics{ctrl: ctrl}
	mock.recorder = &MockAuthMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthMetrics) EXPECT() *MockAuthMetricsMockRecorder {
	return m.recorder
}

// IncLoginError mocks base method.
func (m *MockAuthMetrics) IncLoginError(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncLoginError", reason)
}

// IncLoginError indicates an expected call of IncLoginError.
func (mr *MockAuthMetricsMockRecorder) IncLoginError(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncLoginError", reflect.TypeOf((*MockAuthMetrics)(nil).IncLoginError), reason)
}

// ObserveBcrypt mocks base method.
func (m *MockAuthMetrics) ObserveBcrypt(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveBcrypt", d)
}

// ObserveBcrypt indicates an expected call of ObserveBcrypt.
func (mr *MockAuthMetricsMockRecorder) ObserveBcrypt(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveBcrypt", reflect.TypeOf((*MockAuthMetrics)(nil).ObserveBcrypt), d)
}
