// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=user_mock.go -package=user
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	domain "gmart/internal/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepoIFace is a mock of AuthRepoIFace interface.
type MockAuthRepoIFace struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepoIFaceMockRecorder
	isgomock struct{}
}

// MockAuthRepoIFaceMockRecorder is the mock recorder for MockAuthRepoIFace.
type MockAuthRepoIFaceMockRecorder struct {
	mock *MockAuthRepoIFace
}

// NewMockAuthRepoIFace creates a new mock instance.
func NewMockAuthRepoIFace(ctrl *gomock.Controller) *MockAuthRepoIFace {
	mock := &MockAuthRepoIFace{ctrl: ctrl}
	mock.recorder = &MockAuthRepoIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepoIFace) EXPECT() *MockAuthRepoIFaceMockRecorder {
	return m.recorder
}

// ExpDuration mocks base method.
func (m *MockAuthRepoIFace) ExpDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ExpDuration indicates an expected call of ExpDuration.
func (mr *MockAuthRepoIFaceMockRecorder) ExpDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpDuration", reflect.TypeOf((*MockAuthRepoIFace)(nil).ExpDuration))
}

// RefreshSession mocks base method.
func (m *MockAuthRepoIFace) RefreshSession(ctx context.Context, sessionID domain.SessionID, userAgent domain.UserAgent, ip string) (domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSession", ctx, sessionID, userAgent, ip)
	ret0, _ := ret[0].(domain.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshSession indicates an expected call of RefreshSession.
func (mr *MockAuthRepoIFaceMockRecorder) RefreshSession(ctx, sessionID, userAgent, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSession", reflect.TypeOf((*MockAuthRepoIFace)(nil).RefreshSession), ctx, sessionID, userAgent, ip)
}

// SignIn mocks base method.
func (m *MockAuthRepoIFace) SignIn(ctx context.Context, login domain.Login, password domain.Password, userAgent domain.UserAgent, ip string) (domain.UserID, domain.SessionID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, login, password, userAgent, ip)
	ret0, _ := ret[0].(domain.UserID)
	ret1, _ := ret[1].(domain.SessionID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthRepoIFaceMockRecorder) SignIn(ctx, login, password, userAgent, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthRepoIFace)(nil).SignIn), ctx, login, password, userAgent, ip)
}

// SignInSleep mocks base method.
func (m *MockAuthRepoIFace) SignInSleep(ctx context.Context, login domain.Login, password domain.Password, ua domain.UserAgent, ip string) (domain.UserID, domain.SessionID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInSleep", ctx, login, password, ua, ip)
	ret0, _ := ret[0].(domain.UserID)
	ret1, _ := ret[1].(domain.SessionID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignInSleep indicates an expected call of SignInSleep.
func (mr *MockAuthRepoIFaceMockRecorder) SignInSleep(ctx, login, password, ua, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInSleep", reflect.TypeOf((*MockAuthRepoIFace)(nil).SignInSleep), ctx, login, password, ua, ip)
}

// SignOut mocks base method.
func (m *MockAuthRepoIFace) SignOut(ctx context.Context, sessionID domain.SessionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignOut indicates an expected call of SignOut.
func (mr *MockAuthRepoIFaceMockRecorder) SignOut(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockAuthRepoIFace)(nil).SignOut), ctx, sessionID)
}

// SignUp mocks base method.
func (m *MockAuthRepoIFace) SignUp(ctx context.Context, login domain.Login, password domain.Password, ua domain.UserAgent, ip string) (domain.UserID, domain.SessionID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, login, password, ua, ip)
	ret0, _ := ret[0].(domain.UserID)
	ret1, _ := ret[1].(domain.SessionID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignUp indicates an expected call of SignUp.
func (mr *MockAuthRepoIFaceMockRecorder) SignUp(ctx, login, password, ua, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockAuthRepoIFace)(nil).SignUp), ctx, login, password, ua, ip)
}

// MockTokenGeneratorIFace is a mock of TokenGeneratorIFace interface.
type MockTokenGeneratorIFace struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorIFaceMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorIFaceMockRecorder is the mock recorder for MockTokenGeneratorIFace.
type MockTokenGeneratorIFaceMockRecorder struct {
	mock *MockTokenGeneratorIFace
}

// NewMockTokenGeneratorIFace creates a new mock instance.
func NewMockTokenGeneratorIFace(ctrl *gomock.Controller) *MockTokenGeneratorIFace {
	mock := &MockTokenGeneratorIFace{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGeneratorIFace) EXPECT() *MockTokenGeneratorIFaceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockTokenGeneratorIFace) Generate(userID domain.UserID) (domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", userID)
	ret0, _ := ret[0].(domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockTokenGeneratorIFaceMockRecorder) Generate(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockTokenGeneratorIFace)(nil).Generate), userID)
}
