// Code generated by MockGen. DO NOT EDIT.
// Source: serve.go
//
// Generated by this command:
//
//	mockgen -source=serve.go -destination=serve_mock_test.go -package=serve
//

// Package serve is a generated GoMock package.
package serve
