// Code generated by MockGen. DO NOT EDIT.
// Source: prepared_statement.go
//
// Generated by this command:
//
//	mockgen -source=prepared_statement.go -destination=prepared_statement_mock_test.go -package=pgc
//

// Package pgc is a generated GoMock package.
package pgc

import (
	context "context"
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuery is a mock of Query interface.
type MockQuery[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder[T]
	isgomock struct{}
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder[T any] struct {
	mock *MockQuery[T]
}

// NewMockQuery creates a new mock instance.
func NewMockQuery[T any](ctrl *gomock.Controller) *MockQuery[T] {
	mock := &MockQuery[T]{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery[T]) EXPECT() *MockQueryMockRecorder[T] {
	return m.recorder
}

// Ctx mocks base method.
func (m *MockQuery[T]) Ctx(ctx context.Context, pg PgInstance) Executor[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ctx", ctx, pg)
	ret0, _ := ret[0].(Executor[T])
	return ret0
}

// Ctx indicates an expected call of Ctx.
func (mr *MockQueryMockRecorder[T]) Ctx(ctx, pg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ctx", reflect.TypeOf((*MockQuery[T])(nil).Ctx), ctx, pg)
}

// MockExecutor is a mock of Executor interface.
type MockExecutor[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder[T]
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder[T any] struct {
	mock *MockExecutor[T]
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor[T any](ctrl *gomock.Controller) *MockExecutor[T] {
	mock := &MockExecutor[T]{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor[T]) EXPECT() *MockExecutorMockRecorder[T] {
	return m.recorder
}

// All mocks base method.
func (m *MockExecutor[T]) All(args ...any) iter.Seq2[T, error] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "All", varargs...)
	ret0, _ := ret[0].(iter.Seq2[T, error])
	return ret0
}

// All indicates an expected call of All.
func (mr *MockExecutorMockRecorder[T]) All(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockExecutor[T])(nil).All), args...)
}

// Exec mocks base method.
func (m *MockExecutor[T]) Exec(args ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockExecutorMockRecorder[T]) Exec(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockExecutor[T])(nil).Exec), args...)
}

// One mocks base method.
func (m *MockExecutor[T]) One(args ...any) (T, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "One", varargs...)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// One indicates an expected call of One.
func (mr *MockExecutorMockRecorder[T]) One(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "One", reflect.TypeOf((*MockExecutor[T])(nil).One), args...)
}
