// Code generated by MockGen. DO NOT EDIT.
// Source: prepared_statement.go
//
// Generated by this command:
//
//	mockgen -source=prepared_statement.go -destination=prepared_statement_mock_test.go -package=pgc
//

// Package pgc is a generated GoMock package.
package pgc
