// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -package=workers -destination=repository_mock_test.go -source=repository.go
//

// Package workers is a generated GoMock package.
package workers

import (
	domain "gmart/internal/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkersMetricsRepoIFace is a mock of WorkersMetricsRepoIFace interface.
type MockWorkersMetricsRepoIFace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkersMetricsRepoIFaceMockRecorder
	isgomock struct{}
}

// MockWorkersMetricsRepoIFaceMockRecorder is the mock recorder for MockWorkersMetricsRepoIFace.
type MockWorkersMetricsRepoIFaceMockRecorder struct {
	mock *MockWorkersMetricsRepoIFace
}

// NewMockWorkersMetricsRepoIFace creates a new mock instance.
func NewMockWorkersMetricsRepoIFace(ctrl *gomock.Controller) *MockWorkersMetricsRepoIFace {
	mock := &MockWorkersMetricsRepoIFace{ctrl: ctrl}
	mock.recorder = &MockWorkersMetricsRepoIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkersMetricsRepoIFace) EXPECT() *MockWorkersMetricsRepoIFaceMockRecorder {
	return m.recorder
}

// IncAcquireAttempt mocks base method.
func (m *MockWorkersMetricsRepoIFace) IncAcquireAttempt(found bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncAcquireAttempt", found)
}

// IncAcquireAttempt indicates an expected call of IncAcquireAttempt.
func (mr *MockWorkersMetricsRepoIFaceMockRecorder) IncAcquireAttempt(found any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncAcquireAttempt", reflect.TypeOf((*MockWorkersMetricsRepoIFace)(nil).IncAcquireAttempt), found)
}

// IncOrderFinalized mocks base method.
func (m *MockWorkersMetricsRepoIFace) IncOrderFinalized(status domain.OrderStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncOrderFinalized", status)
}

// IncOrderFinalized indicates an expected call of IncOrderFinalized.
func (mr *MockWorkersMetricsRepoIFaceMockRecorder) IncOrderFinalized(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncOrderFinalized", reflect.TypeOf((*MockWorkersMetricsRepoIFace)(nil).IncOrderFinalized), status)
}

// ObserveDB mocks base method.
func (m *MockWorkersMetricsRepoIFace) ObserveDB(op domain.OpType, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDB", op, duration)
}

// ObserveDB indicates an expected call of ObserveDB.
func (mr *MockWorkersMetricsRepoIFaceMockRecorder) ObserveDB(op, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDB", reflect.TypeOf((*MockWorkersMetricsRepoIFace)(nil).ObserveDB), op, duration)
}

// ObserveListSize mocks base method.
func (m *MockWorkersMetricsRepoIFace) ObserveListSize(size int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveListSize", size)
}

// ObserveListSize indicates an expected call of ObserveListSize.
func (mr *MockWorkersMetricsRepoIFaceMockRecorder) ObserveListSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveListSize", reflect.TypeOf((*MockWorkersMetricsRepoIFace)(nil).ObserveListSize), size)
}
