// Code generated by MockGen. DO NOT EDIT.
// Source: accrual_worker.go
//
// Generated by this command:
//
//	mockgen -package=workers -destination=worker_mock_test.go -source=accrual_worker.go
//

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	domain "gmart/internal/domain"
	dto "gmart/internal/dto"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAccrualClientIFace is a mock of AccrualClientIFace interface.
type MockAccrualClientIFace struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientIFaceMockRecorder
	isgomock struct{}
}

// MockAccrualClientIFaceMockRecorder is the mock recorder for MockAccrualClientIFace.
type MockAccrualClientIFaceMockRecorder struct {
	mock *MockAccrualClientIFace
}

// NewMockAccrualClientIFace creates a new mock instance.
func NewMockAccrualClientIFace(ctrl *gomock.Controller) *MockAccrualClientIFace {
	mock := &MockAccrualClientIFace{ctrl: ctrl}
	mock.recorder = &MockAccrualClientIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClientIFace) EXPECT() *MockAccrualClientIFaceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockAccrualClientIFace) Fetch(ctx context.Context, order domain.OrderNumber) (*dto.AccrualResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, order)
	ret0, _ := ret[0].(*dto.AccrualResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockAccrualClientIFaceMockRecorder) Fetch(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockAccrualClientIFace)(nil).Fetch), ctx, order)
}

// MockWorkerRepoIFace is a mock of WorkerRepoIFace interface.
type MockWorkerRepoIFace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRepoIFaceMockRecorder
	isgomock struct{}
}

// MockWorkerRepoIFaceMockRecorder is the mock recorder for MockWorkerRepoIFace.
type MockWorkerRepoIFaceMockRecorder struct {
	mock *MockWorkerRepoIFace
}

// NewMockWorkerRepoIFace creates a new mock instance.
func NewMockWorkerRepoIFace(ctrl *gomock.Controller) *MockWorkerRepoIFace {
	mock := &MockWorkerRepoIFace{ctrl: ctrl}
	mock.recorder = &MockWorkerRepoIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRepoIFace) EXPECT() *MockWorkerRepoIFaceMockRecorder {
	return m.recorder
}

// AcquireNextOrder mocks base method.
func (m *MockWorkerRepoIFace) AcquireNextOrder(ctx context.Context) (domain.OrderNumber, domain.OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireNextOrder", ctx)
	ret0, _ := ret[0].(domain.OrderNumber)
	ret1, _ := ret[1].(domain.OrderStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcquireNextOrder indicates an expected call of AcquireNextOrder.
func (mr *MockWorkerRepoIFaceMockRecorder) AcquireNextOrder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireNextOrder", reflect.TypeOf((*MockWorkerRepoIFace)(nil).AcquireNextOrder), ctx)
}

// UpdateOrderStatus mocks base method.
func (m *MockWorkerRepoIFace) UpdateOrderStatus(ctx context.Context, orderNumber domain.OrderNumber, orderStatus domain.OrderStatus, accrual domain.Amount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderNumber, orderStatus, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockWorkerRepoIFaceMockRecorder) UpdateOrderStatus(ctx, orderNumber, orderStatus, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockWorkerRepoIFace)(nil).UpdateOrderStatus), ctx, orderNumber, orderStatus, accrual)
}

// MockWorkerMetricsIFace is a mock of WorkerMetricsIFace interface.
type MockWorkerMetricsIFace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMetricsIFaceMockRecorder
	isgomock struct{}
}

// MockWorkerMetricsIFaceMockRecorder is the mock recorder for MockWorkerMetricsIFace.
type MockWorkerMetricsIFaceMockRecorder struct {
	mock *MockWorkerMetricsIFace
}

// NewMockWorkerMetricsIFace creates a new mock instance.
func NewMockWorkerMetricsIFace(ctrl *gomock.Controller) *MockWorkerMetricsIFace {
	mock := &MockWorkerMetricsIFace{ctrl: ctrl}
	mock.recorder = &MockWorkerMetricsIFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerMetricsIFace) EXPECT() *MockWorkerMetricsIFaceMockRecorder {
	return m.recorder
}

// IncProcessed mocks base method.
func (m *MockWorkerMetricsIFace) IncProcessed(result string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncProcessed", result)
}

// IncProcessed indicates an expected call of IncProcessed.
func (mr *MockWorkerMetricsIFaceMockRecorder) IncProcessed(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncProcessed", reflect.TypeOf((*MockWorkerMetricsIFace)(nil).IncProcessed), result)
}

// IncRateLimit mocks base method.
func (m *MockWorkerMetricsIFace) IncRateLimit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRateLimit")
}

// IncRateLimit indicates an expected call of IncRateLimit.
func (mr *MockWorkerMetricsIFaceMockRecorder) IncRateLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRateLimit", reflect.TypeOf((*MockWorkerMetricsIFace)(nil).IncRateLimit))
}

// ObserveRequest mocks base method.
func (m *MockWorkerMetricsIFace) ObserveRequest(code string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveRequest", code, duration)
}

// ObserveRequest indicates an expected call of ObserveRequest.
func (mr *MockWorkerMetricsIFaceMockRecorder) ObserveRequest(code, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveRequest", reflect.TypeOf((*MockWorkerMetricsIFace)(nil).ObserveRequest), code, duration)
}
