// Code generated by MockGen. DO NOT EDIT.
// Source: loyalty.go
//
// Generated by this command:
//
//	mockgen -source=loyalty.go -destination=loyalty_mock_test.go -package=loyalty
//

// Package loyalty is a generated GoMock package.
package loyalty

import (
	context "context"
	domain "gmart/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoyaltyRepoIface is a mock of LoyaltyRepoIface interface.
type MockLoyaltyRepoIface struct {
	ctrl     *gomock.Controller
	recorder *MockLoyaltyRepoIfaceMockRecorder
	isgomock struct{}
}

// MockLoyaltyRepoIfaceMockRecorder is the mock recorder for MockLoyaltyRepoIface.
type MockLoyaltyRepoIfaceMockRecorder struct {
	mock *MockLoyaltyRepoIface
}

// NewMockLoyaltyRepoIface creates a new mock instance.
func NewMockLoyaltyRepoIface(ctrl *gomock.Controller) *MockLoyaltyRepoIface {
	mock := &MockLoyaltyRepoIface{ctrl: ctrl}
	mock.recorder = &MockLoyaltyRepoIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoyaltyRepoIface) EXPECT() *MockLoyaltyRepoIfaceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockLoyaltyRepoIface) GetBalance(ctx context.Context, userID domain.UserID) (domain.Amount, domain.Amount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(domain.Amount)
	ret1, _ := ret[1].(domain.Amount)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockLoyaltyRepoIfaceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockLoyaltyRepoIface)(nil).GetBalance), ctx, userID)
}

// GetWithdrawals mocks base method.
func (m *MockLoyaltyRepoIface) GetWithdrawals(ctx context.Context, userID domain.UserID) ([]domain.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]domain.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockLoyaltyRepoIfaceMockRecorder) GetWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockLoyaltyRepoIface)(nil).GetWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockLoyaltyRepoIface) Withdraw(ctx context.Context, userID domain.UserID, order domain.OrderNumber, amount domain.Amount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, order, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockLoyaltyRepoIfaceMockRecorder) Withdraw(ctx, userID, order, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockLoyaltyRepoIface)(nil).Withdraw), ctx, userID, order, amount)
}
