// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock_test.go -package=loyalty
//

// Package loyalty is a generated GoMock package.
package loyalty

import (
	domain "gmart/internal/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLoyaltyMetrics is a mock of LoyaltyMetrics interface.
type MockLoyaltyMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockLoyaltyMetricsMockRecorder
	isgomock struct{}
}

// MockLoyaltyMetricsMockRecorder is the mock recorder for MockLoyaltyMetrics.
type MockLoyaltyMetricsMockRecorder struct {
	mock *MockLoyaltyMetrics
}

// NewMockLoyaltyMetrics creates a new mock instance.
func NewMockLoyaltyMetrics(ctrl *gomock.Controller) *MockLoyaltyMetrics {
	mock := &MockLoyaltyMetrics{ctrl: ctrl}
	mock.recorder = &MockLoyaltyMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoyaltyMetrics) EXPECT() *MockLoyaltyMetricsMockRecorder {
	return m.recorder
}

// IncWithdrawal mocks base method.
func (m *MockLoyaltyMetrics) IncWithdrawal(status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncWithdrawal", status)
}

// IncWithdrawal indicates an expected call of IncWithdrawal.
func (mr *MockLoyaltyMetricsMockRecorder) IncWithdrawal(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncWithdrawal", reflect.TypeOf((*MockLoyaltyMetrics)(nil).IncWithdrawal), status)
}

// ObserveDB mocks base method.
func (m *MockLoyaltyMetrics) ObserveDB(op domain.OpType, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDB", op, duration)
}

// ObserveDB indicates an expected call of ObserveDB.
func (mr *MockLoyaltyMetricsMockRecorder) ObserveDB(op, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDB", reflect.TypeOf((*MockLoyaltyMetrics)(nil).ObserveDB), op, duration)
}

// ObserveWithdrawalAmount mocks base method.
func (m *MockLoyaltyMetrics) ObserveWithdrawalAmount(amount domain.Amount) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveWithdrawalAmount", amount)
}

// ObserveWithdrawalAmount indicates an expected call of ObserveWithdrawalAmount.
func (mr *MockLoyaltyMetricsMockRecorder) ObserveWithdrawalAmount(amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveWithdrawalAmount", reflect.TypeOf((*MockLoyaltyMetrics)(nil).ObserveWithdrawalAmount), amount)
}
