name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      # 1. Запуск тестов и генерация профиля покрытия
      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      # 2. Генерация отчета и проверка порогов (опционально)
      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.out
          local-prefix: gmart
          # Если покрытие упадет ниже 60%, билд зафейлится
          threshold-file: 60
          # Генерируем бейдж в формате SVG
          git-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: iter1